version: '3.8'

services:
  intake-service:
    build: .docker/local
    image: intake-service
    container_name: intake-service
    volumes:
      - ./internal:/internal
    working_dir: /internal/intake
    ports:
      - "8080:8080"
    networks:
      - heartbeat-network
networks:
  heartbeat-network:
    driver: bridge